export const NIGERIAN_BANKS = [
  { name: 'Access Bank', code: '044' },
  { name: 'First Bank of Nigeria', code: '011' },
  { name: 'Guaranty Trust Bank', code: '058' },
  { name: 'United Bank for Africa', code: '033' },
  { name: 'Zenith Bank', code: '057' },
  { name: 'Wema Bank', code: '035' },
  { name: 'Sterling Bank', code: '232' },
  { name: 'Fidelity Bank', code: '070' },
  { name: 'Polaris Bank', code: '076' },
  { name: 'Heritage Bank', code: '030' },
  { name: 'Keystone Bank', code: '082' },
  { name: 'Titan Trust Bank', code: '102' },
  { name: 'Unity Bank', code: '215' },
  { name: 'Providus Bank', code: '101' },
  { name: 'Stanbic IBTC Bank', code: '221' },
  { name: 'Ecobank Nigeria', code: '050' },
  { name: 'Jaiz Bank', code: '301' },
  { name: 'Taj Bank', code: '302' },
  { name: 'SunTrust Bank', code: '100' },
  { name: 'Parallex Bank', code: '526' },
  { name: 'Premium Trust Bank', code: '527' },
];
